package Gtk2;

our @ISA = qw();

sub action_area {}
sub add_accel_group {}
sub add_events {}
sub add_with_viewport {}
sub allocation {}
sub append {}
sub append_column {}
sub append_item {}
sub append_items {}
sub append_page {}
sub append_set {}
sub apply_tag {}
sub attach {}
sub bg_gc {}
sub can {}
sub can_default {}
sub can_focus {}
sub cancel_button {}
sub child {}
sub clear {}
sub collapse_all {}
sub create_items {}
sub create_pango_layout {}
sub create_tag {}
sub dir_list {}
sub draw_layout {}
sub draw_rectangle {}
sub expand {}
sub expand_all {}
sub fg_gc {}
sub file_list {}
sub free {}
sub get {}
sub get_buffer {}
sub get_char_count {}
sub get_colormap {}
sub get_depth {}
sub get_end_iter {}
sub get_filename {}
sub get_font_desc {}
sub get_group {}
sub get_height {}
sub get_iter_at_offset {}
sub get_language {}
sub get_metrics {}
sub get_modal {}
sub get_pango_context {}
sub get_parent {}
sub get_path {}
sub get_path_str {}
sub get_pixel_size {}
sub get_selected {}
sub get_selection {}
sub get_size {}
sub get_text {}
sub get_vadjustment {}
sub get_widget {}
sub get_width {}
sub grab_default {}
sub grab_focus {}
sub height {}
sub hide {}
sub insert {}
sub insert_text {}
sub iter_children {}
sub iter_has_child {}
sub iter_next {}
sub iter_parent {}
sub keyval {}
sub modify_font {}
sub move {}
sub ok_button {}
sub pack1 {}
sub pack2 {}
sub pack_end {}
sub pack_start {}
sub put {}
sub queue_draw {}
sub realize {}
sub render_to_drawable {}
sub rgb_find_color {}
sub selection_entry {}
sub set {}
sub set_active {}
sub set_back_pixmap {}
sub set_background {}
sub set_border_width {}
sub set_col_spacings {}
sub set_cursor {}
sub set_cursor_visible {}
sub set_editable {}
sub set_filename {}
sub set_focus_vadjustment {}
sub set_headers_visible {}
sub set_justify {}
sub set_layout {}
sub set_markup {}
sub set_minmax_width {}
sub set_modal {}
sub set_mode {}
sub set_name {}
sub set_policy {}
sub set_popdown_strings {}
sub set_position {}
sub set_property {}
sub set_relief {}
sub set_rgb_fg_color {}
sub set_row_spacings {}
sub set_selectable {}
sub set_sensitive {}
sub set_shadow_type {}
sub set_size_request {}
sub set_style {}
sub set_submenu {}
sub set_text {}
sub set_tip {}
sub set_title {}
sub set_transient_for {}
sub set_uposition {}
sub set_visibility {}
sub set_wrap_mode {}
sub shape_combine_mask {}
sub show_all {}
sub signal_connect {}
sub signal_disconnect {}
sub size {}
sub state {}
sub style {}
sub toggle_expansion {}
sub unref {}
sub values {}
sub vbox {}
sub white_gc {}
sub width {}
sub window {}
sub window_position {}
sub Gtk2::x {}

sub bootstrap {}
sub init {}
sub main {}
sub main_quit {}
sub set_locale {}
sub timeout {}
sub timeout_add {}
sub timeout_remove {}
sub update {}
sub update_ui {}
