package Gtk2;

our @ISA = qw();

sub Gtk2::foreach {}
sub Gtk2::x {}
sub XSetInputFocus {}
sub XWINDOW {}
sub action_area {}
sub active {}
sub add_accel_group {}
sub add_attribute {}
sub add_events {}
sub add_with_viewport {}
sub allocation {}
sub allow_grow {}
sub allow_shrink {}
sub append {}
sub append_column {}
sub append_item {}
sub append_items {}
sub append_page {}
sub append_set {}
sub apply_tag {}
sub area {}
sub attach {}
sub bg_gc {}
sub black_gc {}
sub black_gc {}
sub button {}
sub can {}
sub can_default {}
sub can_focus {}
sub cancel_button {}
sub child {}
sub child_position {}
sub children {}
sub clear {}
sub clicked {}
sub collapse_all {}
sub composite {}
sub copy {}
sub create_items {}
sub create_pango_layout {}
sub create_tag {}
sub dir_list {}
sub direction {}
sub disable_activate {}
sub draw {}
sub draw_arc {}
sub draw_drawable {}
sub draw_layout {}
sub draw_rectangle {}
sub entry {}
sub expand {}
sub expand_all {}
sub expand_row {}
sub expand_row {}
sub expand_to_path {}
sub fg_gc {}
sub file_list {}
sub fill {}
sub free {}
sub get {}
sub get_active {}
sub get_buffer {}
sub get_char_count {}
sub get_children {}
sub get_colormap {}
sub get_context_id {}
sub get_cursor {}
sub get_data {}
sub get_depth {}
sub get_end_iter {}
sub get_filename {}
sub get_font_desc {}
sub get_group {}
sub get_height {}
sub get_iter_at_offset {}
sub get_iter_first {}
sub get_language {}
sub get_metrics {}
sub get_modal {}
sub get_model {}
sub get_origin {}
sub get_pango_context {}
sub get_parent {}
sub get_path {}
sub get_path_at_pos {}
sub get_path_str {}
sub get_pixel_size {}
sub get_selected {}
sub get_selection {}
sub get_size {}
sub get_text {}
sub get_vadjustment {}
sub get_value {}
sub get_widget {}
sub get_width {}
sub grab_default {}
sub grab_focus {}
sub height {}
sub hide {}
sub insert {}
sub insert_text {}
sub iter_children {}
sub iter_has_child {}
sub iter_next {}
sub iter_parent {}
sub keyval {}
sub modify_font {}
sub move {}
sub ok_button {}
sub pack1 {}
sub pack2 {}
sub pack_end {}
sub pack_start {}
sub pop {}
sub push {}
sub put {}
sub queue_draw {}
sub realize {}
sub remove_page {}
sub render_to_drawable {}
sub resize {}
sub rgb_find_color {}
sub saturate_and_pixelate {}
sub scroll_to_cell {}
sub select_item {}
sub select_region {}
sub selection_entry {}
sub set {}
sub set_active {}
sub set_back_pixmap {}
sub set_background {}
sub set_border_width {}
sub set_col_spacings {}
sub set_current_page {}
sub set_cursor {}
sub set_cursor_visible {}
sub set_data {}
sub set_default_size {}
sub set_digits {}
sub set_editable {}
sub set_events {}
sub set_filename {}
sub set_focus_vadjustment {}
sub set_fraction {}
sub set_has_window {}
sub set_headers_visible {}
sub set_justify {}
sub set_layout {}
sub set_markup {}
sub set_min_width {}
sub set_minmax_width {}
sub set_modal {}
sub set_mode {}
sub set_model {}
sub set_name {}
sub set_policy {}
sub set_popdown_strings {}
sub set_position {}
sub set_property {}
sub set_relief {}
sub set_rgb_fg_color {}
sub set_row_spacings {}
sub set_selectable {}
sub set_selection_mode {}
sub set_sensitive {}
sub set_shadow_type {}
sub set_size_request {}
sub set_sizing {}
sub set_style {}
sub set_submenu {}
sub set_tab_pos {}
sub set_text {}
sub set_tip {}
sub set_title {}
sub set_transient_for {}
sub set_uposition {}
sub set_use_arrows_always {}
sub set_value {}
sub set_visibility {}
sub set_wrap_mode {}
sub shape_combine_mask {}
sub show_all {}
sub signal_connect {}
sub signal_disconnect {}
sub signal_stop_emission_by_name {}
sub size {}
sub state {}
sub steal {}
sub style {}
sub toggle_expansion {}
sub type {}
sub unref {}
sub values {}
sub vbox {}
sub visible {}
sub white_gc {}
sub widget {}
sub width {}
sub window {}
sub window_position {}
sub y {};#;

sub bootstrap {}
sub equals {}
sub exit {}
sub init {}
sub main {}
sub main_quit {}
sub set_locale {}
sub timeout {}
sub timeout_add {}
sub timeout_remove {}
sub update {}
sub update_ui {}
